##### Clinical Test Mapping #####

clin_test_mapping <- c(
  "pft_complete_base" = "pft_complete",
  "spiro_complete_base" = "spiro_complete",
  "date_of_spirometry_base" = "date_of_spirometry",
  "spirometry_height_base" = "spirometry_height",
  "fev1_l_base" = "fev1_l",
  "fvc_l_base" = "fvc_l",
  "fef_l_base" = "fef_l",

  "pleth_complete_base" = "pleth_complete",
  "date_of_plethysmography_base" = "date_of_plethysmography",
  "plethysmography_height_base" = "plethysmography_height",
  "tlc_base" = "tlc",
  "frc_base" = "frc",
  "rv_base" = "rv",

  "dlco_complete_base" = "dlco_complete",
  "date_of_diffusing_capacity_base" = "date_of_diffusing_capacity",
  "dlco_height_base" = "dlco_height",
  "dlco_base" = "dlco",

  "feno_complete_base" = "feno_complete",
  "date_of_feno_base" = "date_of_feno",
  "feno_ppb_base" = "feno_ppb",

  "micro_complete_base" = "micro_complete",
  "micro_test_date_base" = "micro_test_date",
  "micro_results_base___1" = "micro_results___1",
  "micro_results_base___2" = "micro_results___2",
  "micro_results_base___3" = "micro_results___3",
  "micro_results_base___4" = "micro_results___4",
  "micro_results_base___5" = "micro_results___5",
  "micro_results_base___6" = "micro_results___6",
  "micro_results_base___7" = "micro_results___7",
  "micro_results_base___8" = "micro_results___8",
  "micro_results_base___9" = "micro_results___9",
  "micro_results_base___0" = "micro_results___0",

  "bcc_micro_base" = "bcc_micro",
  "ntm_micro_base" = "ntm_micro",
  "fungal_micro_base" = "fungal_micro",
  "aspergillus_micro_base___1" = "aspergillus_micro___1",
  "other_species_micro_base" = "other_species_micro",

  "sweat_complete_base" = "sweat_complete",
  "sweat_test_date_base" = "sweat_test_date",
  "sweat_meql_base" = "sweat_meql",

  "blood_complete_base" = "blood_complete",

  "trypsinogen_base" = "trypsinogen",
  "trypsinogen_upper_limit_base" = "trypsinogen_upper_limit",
  "trypsinogen_lower_limit_base" = "trypsinogen_lower_limit",
  "trypsinogen_date_base" = "trypsinogen_date",

  "alp_base" = "alp",
  "alp_upper_limit_base" = "alp_upper_limit",
  "alp_lower_limit_base" = "alp_lower_limit",
  "alp_date_base" = "alp_date",

  "ast_base" = "ast",
  "ast_upper_limit_base" = "ast_upper_limit",
  "ast_lower_limit_base" = "ast_lower_limit",
  "ast_date_base" = "ast_date",

  "alt_base" = "alt",
  "alt_upper_limit_base" = "alt_upper_limit",
  "alt_lower_limit_base" = "alt_lower_limit",
  "alt_date_base" = "alt_date",

  "ggt_base" = "ggt",
  "ggt_upper_limit_base" = "ggt_upper_limit",
  "ggt_lower_limit_base" = "ggt_lower_limit",
  "ggt_date_base" = "ggt_date",

  "bilirubin_conj_base" = "bilirubin_conj",
  "bilirubin_conj_upper_limit_base" = "bilirubin_conj_upper_limit",
  "bilirubin_conj_lower_limit_base" = "bilirubin_conj_lower_limit",
  "bilirubin_conj_date_base" = "bilirubin_conj_date",

  "bilirubin_unconj_base" = "bilirubin_unconj",
  "bilirubin_unconj_upper_limit_base" = "bilirubin_unconj_upper_limit",
  "bilirubin_unconj_lower_limit_base" = "bilirubin_unconj_lower_limit",
  "bilirubin_unconj_date_base" = "bilirubin_unconj_date",

  "bilirubin_tot_base" = "bilirubin_tot",
  "bilirubin_tot_upper_limit_base" = "bilirubin_tot_upper_limit",
  "bilirubin_tot_lower_limit_base" = "bilirubin_tot_lower_limit",
  "bilirubin_tot_date_base" = "bilirubin_tot_date",

  "wbc_base" = "wbc",
  "wbc_upper_limit_base" = "wbc_upper_limit",
  "wbc_lower_limit_base" = "wbc_lower_limit",
  "wbc_date_base" = "wbc_date",

  "neutrophils_base" = "neutrophils",
  "neutrophils_upper_limit_base" = "neutrophils_upper_limit",
  "neutrophils_lower_limit_base" = "neutrophils_lower_limit",
  "neutrophil_date_base" = "neutrophil_date",

  "ck_base" = "ck",
  "ck_upper_limit_base" = "ck_upper_limit",
  "ck_lower_limit_base" = "ck_lower_limit",
  "ck_date_base" = "ck_date",

  "eosinophils_base" = "eosinophils",
  "eosinophils_upper_limit_base" = "eosinophils_upper_limit",
  "eosinophils_lower_limit_base" = "eosinophils_lower_limit",
  "eosinophils_date_base" = "eosinophils_date",

  "hemog_a1c_base" = "hemog_a1c",
  "hemog_upper_limit_base" = "hemog_upper_limit",
  "hemog_lower_limit_base" = "hemog_lower_limit",
  "hemoglobin_date_base" = "hemoglobin_date",

  "stool_complete_base" = "stool_complete",
  "stool_test_date_base" = "stool_test_date",
  "fecal_elastase_base" = "fecal_elastase",
  "fecal_elastase_lower_limit_base" = "fecal_elastase_lower_limit",
  "fecal_elastase_detect_base" = "fecal_elastase_detect",

  "exercise_complete_base" = "exercise_complete",
  "exercise_test_date_base" = "exercise_test_date",
  "exercise_test_upload_base" = "exercise_test_upload",

  "ophthal_complete_base" = "ophthal_complete",
  "ophthal_test_date_base" = "ophthal_test_date",
  "opthal_results_normal_base" = "opthal_results_normal",
  "ophthal_abnormality_base___1" = "ophthal_abnormality___1",
  "ophthal_abnormality_base___2" = "ophthal_abnormality___2",
  "ophthal_abnormality_base___0" = "ophthal_abnormality___0",
  "ophthal_other_base" = "ophthal_other",

  "ct_complete_base" = "ct_complete",
  "ct_test_date_base" = "ct_test_date",
  "dicom_upload_base" = "dicom_upload",
  "ct_report_upload_base" = "ct_report_upload",

  "gad7_completed" = "gad7_completed_sub",
  "gad1_base" = "gad1",
  "gad2_base" = "gad2",
  "gad3_base" = "gad3",
  "gad4_base" = "gad4",
  "gad5_base" = "gad5",
  "gad6_base" = "gad6",
  "gad7_base" = "gad7",

  "phq9_completed" = "phq9_completed_sub",
  "phq1_base" = "phq1",
  "phq2_base" = "phq2",
  "phq3_base" = "phq3",
  "phq4_base" = "phq4",
  "phq5_base" = "phq5",
  "phq6_base" = "phq6",
  "phq7_base" = "phq7",
  "phq8_base" = "phq8",
  "phq9_base" = "phq9"
)


##### Clinical Review Mapping #####

clin_rev_mapping <- c(
  "baseline_visit_date" = "visit_date",
  "baseline_specific_resp_symptoms___1" = "specific_resp_symptoms___1",
  "baseline_specific_resp_symptoms___2" = "specific_resp_symptoms___2",
  "baseline_specific_resp_symptoms___0" = "specific_resp_symptoms___0",
  "baseline_other_resp_symptoms" = "other_resp_symptoms",
  "baseline_new_symptoms___1" = "new_symptoms___1",
  "baseline_new_symptoms___2" = "new_symptoms___2",
  "baseline_new_symptoms___0" = "new_symptoms___0",
  "baseline_other_new_symptoms" = "other_new_symptoms",
  "baseline_height" = "height",
  "baseline_weight" = "weight",
  "baseline_bp_systolic" = "bp_systole",
  "baseline_bp_diastolic" = "bp_diastole",
  "baseline_increased_work_breathing" = "increased_work_breathing",
  "baseline_wheeze" = "wheeze",
  "baseline_crackles" = "crackles",
  "baseline_modulator" = "modulator",
  "baseline_modulator_name" = "modulator_name",
  "baseline_iva_dose" = "iva_dose",
  "baseline_iva_freq" = "iva_freq",
  "baseline_iva_freq_other" = "iva_freq_other",
  "baseline_lum_dose" = "lum_dose",
  "baseline_lum_freq" = "lum_freq",
  "baseline_lum_freq_other" = "lum_freq_other",
  "baseline_tez_dose" = "tez_dose",
  "baseline_tez_freq" = "tez_freq",
  "baseline_tez_freq_other" = "tez_freq_other",
  "baseline_elx_dose" = "elx_dose",
  "baseline_elx_freq" = "elx_freq",
  "baseline_elx_freq_other" = "elx_freq_other",
  # "baseline_vanza_dose_1" = "vanza_dose_1",
  # "baseline_vanza_freq_1" = "vanza_freq_1",
  # "baseline_vanza_freq_other_1" = "vanza_freq_other_1",
  # "baseline_deut_dose_1" = "deut_dose_1",
  # "baseline_deut_freq_1" = "deut_freq_1",
  # "baseline_deut_freq_other_1" = "deut_freq_other_1",
  "baseline_preg" = "preg"
)
